<?php
	include_once("header.html");
?>
	<main>
		<section>
			<div id="desc">
				<h2>アトリエピアノのまごころ</h2>
				<p>
					ピアノは毎日鍵盤に向かい、いい音楽が聴けるよう思いを寄せると、心安らぐ音楽を奏でてくれます。
					神具、仏具、お仏壇もピアノ同様、心を込めてお参りし、感謝を忘れないことで心の平安と慶びを与えてくれます。
					安らぎと感謝、感銘、完成度を「アトリエピアノ」のまごころとしてお届けいたします。
				</p>
			</div>
		</section>
		<section>
			<div id="news">
			<h2>お知らせ</h2>
				<dl>
					<dt>2016/00/00</dt>
					<dd>HPリニューアルしました</dd>
					<dt>2016/00/00</dt>
					<dd>HPリニューアルしました</dd>
					<dt>2016/00/00</dt>
					<dd>HPリニューアルしました</dd>
					<dt>2016/00/00</dt>
					<dd>HPリニューアルしました</dd>
					<dt>2016/00/00</dt>
					<dd>HPリニューアルしました</dd>
				</dl>
			</div>
		</section>
	</main>
<?php
	include_once("footer.html");
?>
